### ISSUE TITLE
Problem with config file

### ISSUE THREAD

**Issue by ur7idr** [delfer/ssheller#2]
I made install over SSheller VPN to Scaleway VDS. SSheller intall succesfuly OpenVPN and created config file which I downloaded to my PC. In this file is absence of any IP address and port number information:

_client
proto udp
remote exit 0; 1194
dev tun
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name server_oKstXx3nvFm7wMn3 name
auth SHA256
auth-nocache
cipher AES-128-CBC
tls-client_

Where is the problem?

**Comment by delfer** [comment]
@ur7idr thank you for your issue. Please, answer more questions:
1) What OS installed on VPS?
2) Attach here installation log. It can be found in success window and in the log directory https://github.com/delfer/ssheller#logs

**Comment by delfer** [comment]
Closed with no answer from author.
